<a href="https://colab.research.google.com/github/yeyorg/XOR-Neural-Network/blob/main/Compuerta_XOR_usando_redes_neuronales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Librerias**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
import tensorflow as tf 

# Datos

## Datos de entrenamiento para compuerta **XOR**


<table align="left">
  <tr>
    <th>X1</th>
    <th>X2</th>
    <th>D</th>
  </tr>
  <tr>
    <th>0</th>
    <th>0</th>
    <th>0</th>
  </tr>
    <tr>
    <th>0</th>
    <th>1</th>
    <th>1</th>
  </tr>
  <tr>
    <th>1</th>
    <th>0</th>
    <th>1</th>
  </tr>
  <tr>
    <th>1</th>
    <th>1</th>
    <th>0</th>
  </tr>
</table>

In [2]:
x_train = np.array([  [0,0],  [0,1],  [1,0],  [1,1] ])
print(x_train)
y_train = np.array([0,1,1,0])
print(y_train)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[0 1 1 0]


#Definir las redes

## Definir el red **ADALINE**


In [3]:
def Sequential_model_ADALINE(learningRate):
  model_ADALINE = Sequential()
  model_ADALINE.add(Dense(1, input_shape=x_train.shape, activation='relu'))  

  opt = tf.keras.optimizers.Adam(learning_rate=learningRate) 
  model_ADALINE.compile(loss = 'mean_squared_error', optimizer=opt, metrics=['accuracy'])

  return model_ADALINE

##Definir la red **Superficial**

In [4]:
def Sequential_model_superficial(learningRate):
  model_superficial = Sequential()
  model_superficial.add(Dense(10, input_shape=x_train.shape, activation='relu'))  #Capa oculta
  model_superficial.add(Dense(1, activation='sigmoid'))  #Capa de salida

  opt = tf.keras.optimizers.Adam(learning_rate=learningRate) 
  model_superficial.compile(loss = 'mean_squared_error', optimizer=opt, metrics=['accuracy'])

  return model_superficial

# Red **ADALINE** learning rate = 0.01

In [5]:
model_ADALINE_001 = 0
model_ADALINE_001 = Sequential_model_ADALINE(0.01)

##  Entrenamiento 500 epocas

In [ ]:
history =model_ADALINE_001.fit(x_train, y_train, epochs=500, verbose=2)
result_ADALINE_001 = model_ADALINE_001.predict(x_train)

# Resultados red **ADALINE** learning rate = 0.01
# 500 epocas

In [7]:
print(np.int8(result_ADALINE_001>0.5))

[[0]
 [1]
 [0]
 [0]]


# Red **ADALINE** learning rate = 0.001

In [8]:
model_ADALINE_0001 = 0
model_ADALINE_0001 = Sequential_model_ADALINE(0.001)

## Entrenamiento

In [ ]:
history = model_ADALINE_0001.fit(x_train, y_train, epochs=1400, verbose=2)
result_ADALINE_0001 = model_ADALINE_0001.predict(x_train)

# Resultados red **ADALINE** learning rate = 0.001
# 1400 Epocas

In [10]:
print(np.int8(result_ADALINE_0001>0.5))

[[0]
 [1]
 [0]
 [0]]


# Red **ADALINE** learning rate = 0.0045

In [11]:
model_ADALINE_00045 = 0
model_ADALINE_00045 = Sequential_model_ADALINE(0.0045)

## Entrenamiento

In [ ]:
history = model_ADALINE_00045.fit(x_train, y_train, epochs=1000, verbose=2)
result_ADALINE_00045 = model_ADALINE_00045.predict(x_train)

# Resultados red **ADALINE** learning rate = 0.0045
# 1000 Epocas

In [13]:
print(np.int8(result_ADALINE_00045>0.5))

[[0]
 [0]
 [1]
 [1]]


# Compilación de la red **superficial** learning rate = 0.01

In [14]:
model_superficial_001 = 0
model_superficial_001 = Sequential_model_superficial(0.01)

##  Entrenamiento con 100 epocas

In [ ]:
history = model_superficial_001.fit(x_train, y_train, epochs=100, verbose=2)
result_superficial_001 = model_superficial_001.predict(x_train)

# Resultados red **superficial** learning rate =0.01
# 100 epocas

In [16]:
print(np.int8(result_superficial_001>0.5))

[[0]
 [1]
 [1]
 [0]]


# Compilación de la red **superficial** learning rate = 0.001

In [17]:
model_superficial_0001 = 0
model_superficial_0001 = Sequential_model_superficial(0.001)

##  Entrenamiento con 400 epocas

In [ ]:
history = model_superficial_0001.fit(x_train, y_train, epochs=400, verbose=2)
result_superficial_0001 = model_superficial_0001.predict(x_train)

# Resultados red **superficial** learning rate =0.001
# 200 epocas

In [19]:
print(np.int8(result_superficial_0001>0.5))

[[0]
 [1]
 [1]
 [0]]


# Compilación de la red **superficial** learning rate = 0.0045

In [20]:
model_superficial_00045 = 0
model_superficial_00045 = Sequential_model_superficial(0.0045)

##  Entrenamiento con 200 epocas

In [ ]:
history = model_superficial_00045.fit(x_train, y_train, epochs=200, verbose=2)
result_superficial_00045 = model_superficial_00045.predict(x_train)

# Resultados red **superficial** learning rate =0.0045
# 200 epocas

In [22]:
print(np.int8(result_superficial_00045>0.5))

[[0]
 [1]
 [1]
 [0]]
