<a href="https://colab.research.google.com/github/yeyorg/XOR-Neural-Network/blob/main/Compuerta_XOR_usando_redes_neuronales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Librerias**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
import tensorflow as tf 

# Datos

## Datos de entrenamiento para compuerta **XOR**


<table align="left">
  <tr>
    <th>X1</th>
    <th>X2</th>
    <th>D</th>
  </tr>
  <tr>
    <th>0</th>
    <th>0</th>
    <th>0</th>
  </tr>
    <tr>
    <th>0</th>
    <th>1</th>
    <th>1</th>
  </tr>
  <tr>
    <th>1</th>
    <th>0</th>
    <th>1</th>
  </tr>
  <tr>
    <th>1</th>
    <th>1</th>
    <th>0</th>
  </tr>
</table>

In [2]:
x_train = np.array([  [0,0],  [0,1],  [1,0],  [1,1] ])
print(x_train)
y_train = np.array([0,1,1,0])
print(y_train)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[0 1 1 0]


#Definir las redes

## Definir el red **ADALINE**


In [3]:
def Sequential_model_ADALINE(learningRate):
  model_ADALINE = Sequential()
  model_ADALINE.add(Dense(1, input_shape=x_train.shape, activation='relu'))  

  opt = tf.keras.optimizers.Adam(learning_rate=learningRate) 
  model_ADALINE.compile(loss = 'mean_squared_error', optimizer=opt, metrics=['accuracy'])

  return model_ADALINE

##Definir la red **Superficial**

In [4]:
def Sequential_model_superficial(learningRate):
  model_superficial = Sequential()
  model_superficial.add(Dense(10, input_shape=x_train.shape, activation='relu'))  #Capa oculta
  model_superficial.add(Dense(1, activation='sigmoid'))  #Capa de salida

  opt = tf.keras.optimizers.Adam(learning_rate=learningRate) 
  model_superficial.compile(loss = 'mean_squared_error', optimizer=opt, metrics=['accuracy'])

  return model_superficial

# Red **ADALINE** learning rate = 0.01

In [5]:
model_ADALINE_001 = 0
model_ADALINE_001 = Sequential_model_ADALINE(0.01)

##  Entrenamiento 500 epocas

In [6]:
history =model_ADALINE_001.fit(x_train, y_train, epochs=500, verbose=2)
result_ADALINE_001 = model_ADALINE_001.predict(x_train)

Epoch 1/500
1/1 - 1s - loss: 0.3232 - accuracy: 0.5000
Epoch 2/500
1/1 - 0s - loss: 0.3193 - accuracy: 0.7500
Epoch 3/500
1/1 - 0s - loss: 0.3157 - accuracy: 0.7500
Epoch 4/500
1/1 - 0s - loss: 0.3124 - accuracy: 0.7500
Epoch 5/500
1/1 - 0s - loss: 0.3094 - accuracy: 0.7500
Epoch 6/500
1/1 - 0s - loss: 0.3067 - accuracy: 0.7500
Epoch 7/500
1/1 - 0s - loss: 0.3044 - accuracy: 0.7500
Epoch 8/500
1/1 - 0s - loss: 0.3022 - accuracy: 0.7500
Epoch 9/500
1/1 - 0s - loss: 0.3004 - accuracy: 0.7500
Epoch 10/500
1/1 - 0s - loss: 0.2987 - accuracy: 0.7500
Epoch 11/500
1/1 - 0s - loss: 0.2971 - accuracy: 0.7500
Epoch 12/500
1/1 - 0s - loss: 0.2957 - accuracy: 0.7500
Epoch 13/500
1/1 - 0s - loss: 0.2943 - accuracy: 0.7500
Epoch 14/500
1/1 - 0s - loss: 0.2929 - accuracy: 0.7500
Epoch 15/500
1/1 - 0s - loss: 0.2915 - accuracy: 0.7500
Epoch 16/500
1/1 - 0s - loss: 0.2901 - accuracy: 0.7500
Epoch 17/500
1/1 - 0s - loss: 0.2887 - accuracy: 0.7500
Epoch 18/500
1/1 - 0s - loss: 0.2873 - accuracy: 0.7500
E

# Resultados red **ADALINE** learning rate = 0.01
# 500 epocas

In [7]:
print(np.int8(result_ADALINE_001>0.5))

[[0]
 [1]
 [0]
 [0]]


# Red **ADALINE** learning rate = 0.001

In [8]:
model_ADALINE_0001 = 0
model_ADALINE_0001 = Sequential_model_ADALINE(0.001)

## Entrenamiento

In [9]:
history = model_ADALINE_0001.fit(x_train, y_train, epochs=1400, verbose=2)
result_ADALINE_0001 = model_ADALINE_0001.predict(x_train)

Epoch 1/1400
1/1 - 0s - loss: 0.2669 - accuracy: 0.7500
Epoch 2/1400
1/1 - 0s - loss: 0.2665 - accuracy: 0.7500
Epoch 3/1400
1/1 - 0s - loss: 0.2660 - accuracy: 0.7500
Epoch 4/1400
1/1 - 0s - loss: 0.2656 - accuracy: 0.7500
Epoch 5/1400
1/1 - 0s - loss: 0.2652 - accuracy: 0.7500
Epoch 6/1400
1/1 - 0s - loss: 0.2647 - accuracy: 0.7500
Epoch 7/1400
1/1 - 0s - loss: 0.2643 - accuracy: 0.7500
Epoch 8/1400
1/1 - 0s - loss: 0.2639 - accuracy: 0.7500
Epoch 9/1400
1/1 - 0s - loss: 0.2635 - accuracy: 0.7500
Epoch 10/1400
1/1 - 0s - loss: 0.2631 - accuracy: 0.7500
Epoch 11/1400
1/1 - 0s - loss: 0.2627 - accuracy: 0.7500
Epoch 12/1400
1/1 - 0s - loss: 0.2623 - accuracy: 0.7500
Epoch 13/1400
1/1 - 0s - loss: 0.2620 - accuracy: 0.7500
Epoch 14/1400
1/1 - 0s - loss: 0.2616 - accuracy: 0.7500
Epoch 15/1400
1/1 - 0s - loss: 0.2612 - accuracy: 0.7500
Epoch 16/1400
1/1 - 0s - loss: 0.2609 - accuracy: 0.7500
Epoch 17/1400
1/1 - 0s - loss: 0.2605 - accuracy: 0.7500
Epoch 18/1400
1/1 - 0s - loss: 0.2602 - 

# Resultados red **ADALINE** learning rate = 0.001
# 1400 Epocas

In [10]:
print(np.int8(result_ADALINE_0001>0.5))

[[0]
 [1]
 [0]
 [0]]


# Red **ADALINE** learning rate = 0.0045

In [11]:
model_ADALINE_00045 = 0
model_ADALINE_00045 = Sequential_model_ADALINE(0.0045)

## Entrenamiento

In [12]:
history = model_ADALINE_00045.fit(x_train, y_train, epochs=1000, verbose=2)
result_ADALINE_00045 = model_ADALINE_00045.predict(x_train)

Epoch 1/1000
1/1 - 0s - loss: 0.8678 - accuracy: 0.7500
Epoch 2/1000
1/1 - 0s - loss: 0.8561 - accuracy: 0.7500
Epoch 3/1000
1/1 - 0s - loss: 0.8447 - accuracy: 0.7500
Epoch 4/1000
1/1 - 0s - loss: 0.8334 - accuracy: 0.7500
Epoch 5/1000
1/1 - 0s - loss: 0.8223 - accuracy: 0.7500
Epoch 6/1000
1/1 - 0s - loss: 0.8114 - accuracy: 0.7500
Epoch 7/1000
1/1 - 0s - loss: 0.8006 - accuracy: 0.7500
Epoch 8/1000
1/1 - 0s - loss: 0.7901 - accuracy: 0.7500
Epoch 9/1000
1/1 - 0s - loss: 0.7797 - accuracy: 0.7500
Epoch 10/1000
1/1 - 0s - loss: 0.7696 - accuracy: 0.7500
Epoch 11/1000
1/1 - 0s - loss: 0.7596 - accuracy: 0.7500
Epoch 12/1000
1/1 - 0s - loss: 0.7499 - accuracy: 0.7500
Epoch 13/1000
1/1 - 0s - loss: 0.7403 - accuracy: 0.7500
Epoch 14/1000
1/1 - 0s - loss: 0.7309 - accuracy: 0.7500
Epoch 15/1000
1/1 - 0s - loss: 0.7218 - accuracy: 0.7500
Epoch 16/1000
1/1 - 0s - loss: 0.7128 - accuracy: 0.7500
Epoch 17/1000
1/1 - 0s - loss: 0.7041 - accuracy: 0.7500
Epoch 18/1000
1/1 - 0s - loss: 0.6955 - 

# Resultados red **ADALINE** learning rate = 0.0045
# 1000 Epocas

In [13]:
print(np.int8(result_ADALINE_00045>0.5))

[[0]
 [0]
 [1]
 [1]]


# Compilación de la red **superficial** learning rate = 0.01

In [14]:
model_superficial_001 = 0
model_superficial_001 = Sequential_model_superficial(0.01)

##  Entrenamiento con 100 epocas

In [15]:
history = model_superficial_001.fit(x_train, y_train, epochs=100, verbose=2)
result_superficial_001 = model_superficial_001.predict(x_train)

Epoch 1/100
1/1 - 0s - loss: 0.2593 - accuracy: 0.5000
Epoch 2/100
1/1 - 0s - loss: 0.2562 - accuracy: 0.5000
Epoch 3/100
1/1 - 0s - loss: 0.2540 - accuracy: 0.5000
Epoch 4/100
1/1 - 0s - loss: 0.2519 - accuracy: 0.5000
Epoch 5/100
1/1 - 0s - loss: 0.2498 - accuracy: 0.5000
Epoch 6/100
1/1 - 0s - loss: 0.2477 - accuracy: 0.7500
Epoch 7/100
1/1 - 0s - loss: 0.2457 - accuracy: 0.7500
Epoch 8/100
1/1 - 0s - loss: 0.2437 - accuracy: 0.7500
Epoch 9/100
1/1 - 0s - loss: 0.2417 - accuracy: 0.7500
Epoch 10/100
1/1 - 0s - loss: 0.2402 - accuracy: 1.0000
Epoch 11/100
1/1 - 0s - loss: 0.2392 - accuracy: 1.0000
Epoch 12/100
1/1 - 0s - loss: 0.2381 - accuracy: 0.7500
Epoch 13/100
1/1 - 0s - loss: 0.2369 - accuracy: 0.7500
Epoch 14/100
1/1 - 0s - loss: 0.2356 - accuracy: 0.7500
Epoch 15/100
1/1 - 0s - loss: 0.2344 - accuracy: 0.7500
Epoch 16/100
1/1 - 0s - loss: 0.2332 - accuracy: 0.7500
Epoch 17/100
1/1 - 0s - loss: 0.2320 - accuracy: 0.7500
Epoch 18/100
1/1 - 0s - loss: 0.2308 - accuracy: 0.7500
E

# Resultados red **superficial** learning rate =0.01
# 100 epocas

In [16]:
print(np.int8(result_superficial_001>0.5))

[[0]
 [1]
 [1]
 [0]]


# Compilación de la red **superficial** learning rate = 0.001

In [17]:
model_superficial_0001 = 0
model_superficial_0001 = Sequential_model_superficial(0.001)

##  Entrenamiento con 400 epocas

In [18]:
history = model_superficial_0001.fit(x_train, y_train, epochs=400, verbose=2)
result_superficial_0001 = model_superficial_0001.predict(x_train)

Epoch 1/400
1/1 - 0s - loss: 0.2548 - accuracy: 0.7500
Epoch 2/400
1/1 - 0s - loss: 0.2545 - accuracy: 0.5000
Epoch 3/400
1/1 - 0s - loss: 0.2541 - accuracy: 0.7500
Epoch 4/400
1/1 - 0s - loss: 0.2538 - accuracy: 0.7500
Epoch 5/400
1/1 - 0s - loss: 0.2534 - accuracy: 0.7500
Epoch 6/400
1/1 - 0s - loss: 0.2531 - accuracy: 0.7500
Epoch 7/400
1/1 - 0s - loss: 0.2528 - accuracy: 0.7500
Epoch 8/400
1/1 - 0s - loss: 0.2524 - accuracy: 0.7500
Epoch 9/400
1/1 - 0s - loss: 0.2521 - accuracy: 0.7500
Epoch 10/400
1/1 - 0s - loss: 0.2518 - accuracy: 0.7500
Epoch 11/400
1/1 - 0s - loss: 0.2514 - accuracy: 0.7500
Epoch 12/400
1/1 - 0s - loss: 0.2511 - accuracy: 0.7500
Epoch 13/400
1/1 - 0s - loss: 0.2508 - accuracy: 0.7500
Epoch 14/400
1/1 - 0s - loss: 0.2505 - accuracy: 0.7500
Epoch 15/400
1/1 - 0s - loss: 0.2502 - accuracy: 0.7500
Epoch 16/400
1/1 - 0s - loss: 0.2499 - accuracy: 0.7500
Epoch 17/400
1/1 - 0s - loss: 0.2496 - accuracy: 0.7500
Epoch 18/400
1/1 - 0s - loss: 0.2493 - accuracy: 0.7500
E

# Resultados red **superficial** learning rate =0.001
# 200 epocas

In [19]:
print(np.int8(result_superficial_0001>0.5))

[[0]
 [1]
 [1]
 [0]]


# Compilación de la red **superficial** learning rate = 0.0045

In [20]:
model_superficial_00045 = 0
model_superficial_00045 = Sequential_model_superficial(0.0045)

##  Entrenamiento con 200 epocas

In [21]:
history = model_superficial_00045.fit(x_train, y_train, epochs=200, verbose=2)
result_superficial_00045 = model_superficial_00045.predict(x_train)

Epoch 1/200
1/1 - 0s - loss: 0.2817 - accuracy: 0.5000
Epoch 2/200
1/1 - 0s - loss: 0.2796 - accuracy: 0.2500
Epoch 3/200
1/1 - 0s - loss: 0.2775 - accuracy: 0.2500
Epoch 4/200
1/1 - 0s - loss: 0.2754 - accuracy: 0.2500
Epoch 5/200
1/1 - 0s - loss: 0.2736 - accuracy: 0.2500
Epoch 6/200
1/1 - 0s - loss: 0.2718 - accuracy: 0.0000e+00
Epoch 7/200
1/1 - 0s - loss: 0.2702 - accuracy: 0.2500
Epoch 8/200
1/1 - 0s - loss: 0.2686 - accuracy: 0.2500
Epoch 9/200
1/1 - 0s - loss: 0.2672 - accuracy: 0.2500
Epoch 10/200
1/1 - 0s - loss: 0.2657 - accuracy: 0.2500
Epoch 11/200
1/1 - 0s - loss: 0.2644 - accuracy: 0.2500
Epoch 12/200
1/1 - 0s - loss: 0.2631 - accuracy: 0.2500
Epoch 13/200
1/1 - 0s - loss: 0.2619 - accuracy: 0.2500
Epoch 14/200
1/1 - 0s - loss: 0.2608 - accuracy: 0.2500
Epoch 15/200
1/1 - 0s - loss: 0.2596 - accuracy: 0.2500
Epoch 16/200
1/1 - 0s - loss: 0.2585 - accuracy: 0.2500
Epoch 17/200
1/1 - 0s - loss: 0.2574 - accuracy: 0.2500
Epoch 18/200
1/1 - 0s - loss: 0.2565 - accuracy: 0.25

# Resultados red **superficial** learning rate =0.0045
# 200 epocas

In [22]:
print(np.int8(result_superficial_00045>0.5))

[[0]
 [1]
 [1]
 [0]]
